# Generated by Django 3.2.8 on 2021-11-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pkob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Phone_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.IntegerField(),
        ),
    ]
