# Generated by Django 3.2.8 on 2021-11-11 05:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pkob', '0002_auto_20211109_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='Timestamp',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
