# Generated by Django 3.2.8 on 2021-11-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pkob', '0004_auto_20211111_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='age',
        ),
    ]
