# Generated by Django 3.2.8 on 2021-12-18 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pkob', '0007_alter_people_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
