# Generated by Django 3.2.8 on 2021-12-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pkob', '0012_remove_people_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
