# Generated by Django 3.2.8 on 2021-12-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Pkob', '0013_people_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='Timestamp',
            new_name='timestamp',
        ),
    ]
